# Generated by Django 4.2.6 on 2023-12-27 03:57

import app_core.models.md_manage_file_excel
import app_core.models.md_manage_geojson
import app_core.models.md_manage_shapefile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDynamicFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định xem đối tượng này còn được coi là đang hoạt động. Bạn nên bỏ chọn này thay vì xóa đối tượng.', verbose_name='Hoạt động')),
                ('name_display', models.CharField(max_length=255, verbose_name='Tên hiển thị')),
                ('model', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thẻ tên')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('public', models.BooleanField(default=False, help_text='Chế độ công khai')),
                ('construct', models.JSONField(default=dict, editable=False)),
                ('use_geom', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_model_dynamic_folder', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
            ],
            options={
                'verbose_name': 'Model dynamic - thư mục',
                'verbose_name_plural': 'Các liên kết giữa model và thư mục',
                'db_table': 'tb_model_dynamic_folder',
            },
        ),
        migrations.CreateModel(
            name='TemplateDynamicModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định xem đối tượng này còn được coi là đang hoạt động. Bạn nên bỏ chọn này thay vì xóa đối tượng.', verbose_name='Hoạt động')),
                ('name', models.CharField(max_length=100, verbose_name='Tên mẫu cấu trúc')),
                ('construct', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Mẫu dữ liệu động (Template model dynamic)',
                'verbose_name_plural': 'Các mẫu dữ liệu động)',
                'db_table': 'tb_template_dynamic_model',
            },
        ),
        migrations.CreateModel(
            name='PinDynamic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.modeldynamicfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Dynamic được gim',
                'db_table': 'tb_model_dynamic_pin',
                'default_permissions': [],
                'unique_together': {('user', 'data')},
            },
        ),
        migrations.AddField(
            model_name='modeldynamicfolder',
            name='pin',
            field=models.ManyToManyField(related_name='dynamic_pin', through='app_core.PinDynamic', to=settings.AUTH_USER_MODEL, verbose_name='Ghim'),
        ),
        migrations.AddField(
            model_name='modeldynamicfolder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_model_dynamic_folder', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.CreateModel(
            name='ManageShapeFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hiển thị')),
                ('app_name', models.CharField(max_length=50)),
                ('shape_file', models.FileField(upload_to=app_core.models.md_manage_shapefile.upload_to, verbose_name='Shapefile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_shape_file', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
            ],
            options={
                'verbose_name': 'Quản lý shapefile',
                'verbose_name_plural': 'Quản lý shapefile',
                'db_table': 'tb_manage_shapefile',
            },
        ),
        migrations.CreateModel(
            name='ManageGeojsonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hiển thị')),
                ('app_name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=app_core.models.md_manage_geojson.upload_to, verbose_name='File Geojson')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='Geojson')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_geojson', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
            ],
            options={
                'verbose_name': 'Quản lý file geojson',
                'verbose_name_plural': 'Quản lý file geojson',
                'db_table': 'tb_manage_geojson_file',
            },
        ),
        migrations.CreateModel(
            name='ManageFileExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hiển thị')),
                ('app_name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=app_core.models.md_manage_file_excel.upload_to, verbose_name='File excel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cre_excel', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
            ],
            options={
                'verbose_name': 'Quản lý file excel',
                'verbose_name_plural': 'Quản lý file excel',
                'db_table': 'tb_manage_file_excel',
            },
        ),
    ]
