# Generated by Django 4.2.6 on 2023-12-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managefileexcelmodel',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='managegeojsonmodel',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='manageshapefilemodel',
            name='app_name',
        ),
    ]
