# Generated by Django 4.2.6 on 2023-12-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('use_uuid', models.BooleanField(default=False, editable=False)),
                ('use_object3d', models.BooleanField(default=False, editable=False)),
                ('_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mô hình dữ liệu',
                'verbose_name_plural': 'Các mô hình dữ liệu',
                'db_table': 'tb_core_models_schema',
            },
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('data_type', models.CharField(choices=[('image', 'image'), ('file', 'file'), ('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('point', 'point'), ('linestring', 'linestring'), ('polygon', 'polygon'), ('geometry', 'geometry'), ('multipolygon', 'multipolygon'), ('json', 'json'), ('foreignkey', 'foreignkey')], editable=False, max_length=16)),
                ('null', models.BooleanField(default=False)),
                ('blank', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(null=True)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_foreign', models.CharField(blank=True, max_length=255, null=True)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
                ('model_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app_dynamic.modelschema')),
            ],
            options={
                'verbose_name': 'Trường trong mô hình dữ liệu',
                'verbose_name_plural': 'Các trường trong mô hình dữ liệu',
                'db_table': 'tb_core_fields_schema',
            },
        ),
    ]
